use 5.006;
use strict;
use warnings;
use ExtUtils::MakeMaker;

WriteMakefile(
    NAME                => 'PidFile',
    AUTHOR              => q{Lukasz Romanowski <dr.romanowski@gmail.com>},
    VERSION_FROM        => 'lib/PidFile.pm',
    ABSTRACT_FROM       => 'lib/PidFile.pm',
    ($ExtUtils::MakeMaker::VERSION >= 6.3002
      ? ('LICENSE'=> 'perl')
      : ()),
    PL_FILES            => {},
    PREREQ_PM => {
        'Test::More' => 0,
    },
    dist                => { COMPRESS => 'gzip -9f', SUFFIX => 'gz', },
    clean               => { FILES => 'PidFile-*' },
);
